config/routes.rb
Rails.application.routes.draw do
  get '/gdrive_files' => 'google_oauths#get_drive_files', as: :gdrive_files
  get '/gdrive_files/callback' => 'google_oauths#get_drive_files_callback'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees

  resources :users

  resources :services

  resources :slackbots

  resources :trellobots

  resources :google_oauths, only: [:new]

  resources :jobs do
		resources :slacksubscriptions, only: [:new]
	end

	resources :slacksubscriptions, only: [:create]

  resources :jobs do
    resources :trellosubscriptions, only: [:new]
  end

  resources :trellosubscriptions, only: [:create]

  resources :jobs do
    resources :googlesubscriptions, only: [:new]
  end

  resources :googlesubscriptions, only: [:create]



  root 'employees#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord

	belongs_to :user
	belongs_to :job
	
end

app/models/gfolder.rb
class Gfolder < ApplicationRecord
	belongs_to :google_oauth

	has_many :googlesubscriptions, dependent: :destroy
	has_many :jobs, through: :googlesubscriptions

end

app/models/google_oauth.rb
class GoogleOauth < ActiveRecord::Base
	belongs_to :user
	belongs_to :service
	has_many :gfolders, dependent: :destroy
	

end

app/models/googlesubscription.rb
class Googlesubscription < ApplicationRecord

	belongs_to :gfolder
	belongs_to :job
	
end

app/models/job.rb
class Job < ApplicationRecord

	belongs_to :user
	has_many :employees
	
	has_many :slacksubscriptions, dependent: :destroy
	has_many :slackchannels, through: :slacksubscriptions

	has_many :trellosubscriptions, dependent: :destroy
	has_many :trelloteams, through: :trellosubscriptions

	has_many :googlesubscriptions, dependent: :destroy
	has_many :gfolders, through: :googlesubscriptions
	
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :slackbots, dependent: :destroy

	has_many :servicesubscriptions, dependent: :destroy
	has_many :users, through: :servicesubscriptions
	
	has_many :trellobots, dependent: :destroy

	has_many :google_oauths, dependent: :destroy
end

app/models/servicesubscription.rb
class Servicesubscription < ApplicationRecord

	belongs_to :service
	belongs_to :user
	
end

app/models/slack_invitation.rb
require 'watir'
 
 module SlackInvitation
   class Invitator
 
     attr_writer :team, :admin_email, :admin_password
 
     def initialize
       @driver = nil
       @headless = nil
     end
     
     def start
       @driver = Watir::Browser.new :chrome  
     end
 
     def quit
       @driver.quit
     end
 
     # def headless_start
     #   @headless = Headless.new
     #   @headless.start
     # end
     
     # def headless_destroy
     #   @headless.destroy
     # end
     
     def invite(email)
       login
       send_invitation_mail(email)
       # test_success
     end
 
     def config(team, email, password)
       @team = team
       @admin_email = email
       @admin_password = password
     end
 
     private
     
     def login
       @driver.goto slack_url
       @driver.text_field(:id => 'email').set (@admin_email)
       @driver.text_field(:id => 'password').set (@admin_password)
       @driver.button(:id, 'signin_btn').click
       true
     end
 
     def send_invitation_mail(email)
       return false if email !~ /@/
       
       tries ||= 
       wait tries
       # @driver.goto slack_url
       @driver.button(:id, "channel_list_invites_link").click  
       wait tries
       @driver.text_field(:name, 'email_address').set (email)
       @driver.button(:id, 'admin_invites_submit_btn').click
       wait tries
     end
 
     # def test_success
     #   error = @driver.find_element(:class, 'error_msg').displayed?
     #   success = @driver.find_element(:class, 'seafoam_green').displayed?
 
     #   return true if success
     #   return false if error
     # end
     
     def slack_url
       "http://#{ @team }.slack.com/"
     end
 
     # def invitation_url
     #   "https://#{ @team }.slack.com/"   
     # end
     
     def wait(try = nil)
       sleep(3) unless try
       sleep(0.5 + try*1) if try
     end
   end
 end

app/models/slackbot.rb
class Slackbot < ApplicationRecord

	belongs_to :user
	belongs_to :service
	has_many :slackchannels, dependent: :destroy
	
end

app/models/slackchannel.rb
class Slackchannel < ApplicationRecord
	belongs_to :slackbot

	has_many :slacksubscriptions, dependent: :destroy
	has_many :jobs, through: :slacksubscriptions

end

app/models/slacksubscription.rb
class Slacksubscription < ApplicationRecord

	belongs_to :slackchannel
	belongs_to :job
	
end

app/models/trellobot.rb
class Trellobot < ApplicationRecord

	belongs_to :user
	belongs_to :service
	has_many :trelloteams, dependent: :destroy
	
end

app/models/trellosubscription.rb
class Trellosubscription < ApplicationRecord

	belongs_to :trelloteam
	belongs_to :job
	
end

app/models/trelloteam.rb
class Trelloteam < ApplicationRecord
	belongs_to :trellobot

	has_many :trellosubscriptions, dependent: :destroy
	has_many :jobs, through: :trellosubscriptions

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :google_oauths, dependent: :destroy

  has_many :employees, dependent: :destroy
  has_many :slackbots, dependent: :destroy 
  has_many :jobs, dependent: :destroy
  has_many :trellobots, dependent: :destroy

  has_many :servicesubscriptions, dependent: :destroy
	has_many :services, through: :servicesubscriptions


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController


	def new
		@job = Job.new
	end

	def create
		@job = Job.create(job_params)
		redirect_to job_path(@job)
	end

	def show
		@job = Job.find(params[:id])
		@services = current_user.services
	end

	private
	def job_params
		params.require(:job).permit(:position, :user_id)
	end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController


	def index
		@services = Service.where(supported?: 1)
		@slackbot_count = current_user.slackbots.count
		@trellobot_count = current_user.trellobots.count
		@google_oauth_count = current_user.google_oauths.count
	end




# 	def create
# 		@slackbot = current_user.slackbots.new(bot_params)

# 	end

# 	private
# 	def employee_params
# 		params.require(:slackbot).permit(:authenticity_token, :service_id, :user_id)
# 	end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/google_oauth_helper.rb
module GoogleOauthHelper
end

app/views/jobs/new.html.erb
<h1> Add a new job! </h1>

<%= form_for (@job) do |f| %>
	<%= f.label :position %>
	<%= f.text_field :position %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.submit "Next" %>
<% end %> 

app/views/jobs/show.html.erb
<h1> Subscription options for your <%=@job.position.downcase%> </h1>

<% @services.each do |s| %>
	<%= s.name %>
	<% if s.name == "Slack" %>
		<%= link_to "Add", new_job_slacksubscription_path(job_id: @job.id) %>
		<br>
	<% elsif s.name == "Trello" %>
		<%= link_to "Add", new_job_trellosubscription_path(job_id: @job.id) %>
		<br>
	<% elsif s.name == "Gdrive" %>
		<%= link_to "Add", new_job_googlesubscription_path(job_id: @job.id) %>
	<% end %>
<% end %>

app/views/services/index.html.erb
<h1> Subscribe to services now! </h1>

<% @services.each do |s| %>
	Name: <%= s.name %>
	<br>
	What it does: <%= s.description %>
	<br>
	<% if s.name == "Slack" %>
		Slack teams added: <%= @slackbot_count %>
		<br>
		<%= link_to "Subscribe", new_slackbot_path %>		
	
		<br>
		<br>
		<br>
	<% elsif s.name == "Trello" %>
		Trello accounts added: <%= @trellobot_count %>
		<br>
		<%= link_to "Subscribe", new_trellobot_path %>

		<br>
		<br>
		<br>
	<% elsif s.name == "Gdrive" %>
		Google accounts added: <%= @google_oauth_count %>
		<br>
		<%= link_to "Subscribe", new_google_oauth_path %>

	<% end %>
<% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>